//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceShoesWeb.Context_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangNhapNQT
    {
        public int Id { get; set; }
        public Nullable<int> IdNQT { get; set; }
        public string EmailNQT { get; set; }
        public string MatKhauNQT { get; set; }
    }
}
