//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceShoesWeb.Context_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatHang
    {
        public int Id { get; set; }
        public Nullable<int> IdKH { get; set; }
        public string TenKH { get; set; }
        public string TenSP { get; set; }
        public Nullable<System.DateTime> TrangThaiDH { get; set; }
    }
}
